// PPP Shared Booking Service
// 1. Create a Google Sheet and open Extensions -> Apps Script.
// 2. Paste this file, run setupPPPBooking(), and copy the logged admin key.
// 3. Deploy as Web app: execute as yourself; access: anyone.
// 4. Paste the /exec URL and admin key into PPP Settings -> Shared booking connection.
const PPP_BOOKING_SHEET_NAME='Requests';
const PPP_BOOKING_HEADERS=['id','createdAt','name','email','type','what','date','time','timezone','duration','note','status','calendarEventId'];

function doGet(e){
  const p=e&&e.parameter||{},action=String(p.action||'').toLowerCase();
  if(!action)return HtmlService.createHtmlOutput(publicBookingPage_()).setTitle('Book with Pratik').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  const callback=safeCallback_(p.callback);
  try{requireAdminKey_(p.key);let payload;if(action==='list')payload={ok:true,requests:listRequests_()};else if(action==='accept')payload={ok:true,request:updateRequestStatus_(p.id,'accepted')};else if(action==='decline')payload={ok:true,request:deleteRequest_(p.id)};else payload={ok:false,error:'Unknown action'};return jsonOrJsonp_(payload,callback)}catch(error){return jsonOrJsonp_({ok:false,error:String(error&&error.message||error)},callback)}
}
function doPost(e){try{return HtmlService.createHtmlOutput(successPage_(createRequest_(e&&e.parameter||{}))).setTitle('Request sent')}catch(error){return HtmlService.createHtmlOutput(messagePage_('Could not send request',String(error&&error.message||error),'#ff5d6c')).setTitle('Could not send request')}}
function setupPPPBooking(){const properties=PropertiesService.getScriptProperties();if(!properties.getProperty('ADMIN_KEY'))properties.setProperty('ADMIN_KEY',Utilities.getUuid().replace(/-/g,''));ensureSheet_();Logger.log('ADMIN KEY: '+properties.getProperty('ADMIN_KEY'));Logger.log('Deploy as a Web app, then copy the /exec URL into PPP Settings.')}
function getPPPBookingAdminKey(){const key=PropertiesService.getScriptProperties().getProperty('ADMIN_KEY');if(!key)throw new Error('Run setupPPPBooking() first.');Logger.log(key);return key}
function requireAdminKey_(key){const expected=PropertiesService.getScriptProperties().getProperty('ADMIN_KEY');if(!expected)throw new Error('Run setupPPPBooking() first.');if(String(key||'')!==expected)throw new Error('Invalid admin key.')}
function ensureSheet_(){const spreadsheet=SpreadsheetApp.getActiveSpreadsheet();if(!spreadsheet)throw new Error('This script must be attached to a Google Sheet.');let sheet=spreadsheet.getSheetByName(PPP_BOOKING_SHEET_NAME);if(!sheet)sheet=spreadsheet.insertSheet(PPP_BOOKING_SHEET_NAME);if(sheet.getLastRow()===0)sheet.appendRow(PPP_BOOKING_HEADERS);return sheet}
function clean_(value,max){return String(value==null?'':value).trim().slice(0,max)}
function normalizeBookingTime_(raw){let value=String(raw==null?'':raw).trim().toLowerCase().replace(/\./g,'').replace(/\s+/g,''),period='';const suffix=value.match(/(am|pm)$/);if(suffix){period=suffix[1];value=value.slice(0,-2)}let hours,minutes;if(value.indexOf(':')>=0){const parts=value.split(':');hours=Number(parts[0]);minutes=Number(parts[1])}else{const digits=value.replace(/\D/g,'');if(!digits||digits.length>4)return '';if(digits.length<=2){hours=Number(digits);minutes=0}else if(digits.length===3){hours=Number(digits.slice(0,1));minutes=Number(digits.slice(1))}else{hours=Number(digits.slice(0,2));minutes=Number(digits.slice(2))}}if(!Number.isInteger(hours)||!Number.isInteger(minutes)||minutes<0||minutes>59)return '';if(period){if(hours<1||hours>12)return '';if(period==='am')hours=hours===12?0:hours;else hours=hours===12?12:hours+12}if(hours<0||hours>23)return '';return String(hours).padStart(2,'0')+':'+String(minutes).padStart(2,'0')}
function createRequest_(p){
  const name=clean_(p.name,80),email=clean_(p.email,120),type=clean_(p.type||'Appointment',50),what=clean_(p.what,140),date=clean_(p.date,10),time=normalizeBookingTime_(p.time),timezone=clean_(p.timezone||Session.getScriptTimeZone()||'Europe/Berlin',80),duration=Math.max(15,Math.min(240,Number(p.duration)||30)),note=clean_(p.note,500);
  if(!name)throw new Error('Please enter your name.');if(email&&!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))throw new Error('Please enter a valid email.');if(!what)throw new Error('Please say what the booking is for.');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error('Please choose a date.');if(!time)throw new Error('Please enter a valid time.');
  const row=['req_'+Utilities.getUuid().slice(0,8)+'_'+Date.now(),new Date().toISOString(),name,email,type,what,date,time,timezone,duration,note,'pending',''];ensureSheet_().appendRow(row);return rowToObject_(row);
}
function listRequests_(){const values=ensureSheet_().getDataRange().getValues();return values.length<=1?[]:values.slice(1).map(rowToObject_).filter(function(request){return request.id}).sort(function(a,b){return String(b.createdAt).localeCompare(String(a.createdAt))})}
function rowToObject_(row){const object={};PPP_BOOKING_HEADERS.forEach(function(header,index){object[header]=row[index] instanceof Date?row[index].toISOString():row[index]});return object}
function bookingDateTime_(date,time,timezone){return Utilities.parseDate(date+' '+time,timezone||Session.getScriptTimeZone(),'yyyy-MM-dd HH:mm')}
function updateRequestStatus_(id,status){const sheet=ensureSheet_(),values=sheet.getDataRange().getValues();for(let index=1;index<values.length;index++){if(String(values[index][0])!==String(id))continue;const row=values[index];row[11]=status;if(status==='accepted'&&!row[12]){const start=bookingDateTime_(String(row[6]).slice(0,10),normalizeBookingTime_(row[7]),row[8]),end=new Date(start.getTime()+(Number(row[9])||30)*60000),description=['Requested by: '+row[2],row[3]?'Email: '+row[3]:'','Type: '+row[4],row[10]?'Note: '+row[10]:'','PPP request: '+row[0]].filter(Boolean).join('\n'),options={description:description};if(row[3])options.guests=row[3];const event=CalendarApp.getDefaultCalendar().createEvent(row[5]||row[4],start,end,options);row[12]=event.getId()}sheet.getRange(index+1,1,1,PPP_BOOKING_HEADERS.length).setValues([row]);return rowToObject_(row)}throw new Error('Request not found.')}
function deleteRequest_(id){const sheet=ensureSheet_(),values=sheet.getDataRange().getValues();for(let index=1;index<values.length;index++){if(String(values[index][0])===String(id)){sheet.deleteRow(index+1);return {id:id,deleted:true}}}throw new Error('Request not found.')}
function safeCallback_(value){const callback=String(value||'');return /^[A-Za-z_$][0-9A-Za-z_$\.]*$/.test(callback)?callback:''}
function jsonOrJsonp_(payload,callback){const json=JSON.stringify(payload);return ContentService.createTextOutput(callback?callback+'('+json+');':json).setMimeType(ContentService.MimeType.JAVASCRIPT)}
function escapeHtml_(value){return String(value==null?'':value).replace(/[&<>"']/g,function(character){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]})}
function publicBookingPage_(){
  const timezone=Session.getScriptTimeZone()||'Europe/Berlin';return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Book with me</title><style>*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:20px;background:#071426;color:#edf4ff;font:15px system-ui}main{width:min(620px,100%);padding:28px;border:1px solid #284568;border-radius:24px;background:#0d213c;box-shadow:0 24px 70px #0007}h1{margin:0 0 6px;font-size:2rem}p{color:#9bb0cc;line-height:1.5}form{display:grid;grid-template-columns:1fr 1fr;gap:13px;margin-top:22px}label{display:grid;gap:6px;color:#aebfd5;font-size:.78rem;font-weight:700}.wide{grid-column:1/-1}input,select,textarea,button{font:inherit;border-radius:11px;padding:12px;border:1px solid #2b486b;background:#091a31;color:#edf4ff}textarea{min-height:95px;resize:vertical}button{grid-column:1/-1;border:0;background:linear-gradient(135deg,#4f8cff,#9b6cff);font-weight:900;cursor:pointer}@media(max-width:560px){form{grid-template-columns:1fr}.wide{grid-column:auto}}</style></head><body><main><h1>Request an appointment</h1><p>Choose a preferred time. Your request remains pending until Pratik accepts it.</p><form method="post"><label>Your name *<input name="name" maxlength="80" required></label><label>Email<input name="email" type="email" maxlength="120"></label><label class="wide">What is this for? *<input name="what" maxlength="140" required></label><label>Type<select name="type"><option>Appointment</option><option>Study session</option><option>Call</option><option>Meeting</option></select></label><label>Duration<select name="duration"><option value="30">30 minutes</option><option value="45">45 minutes</option><option value="60">60 minutes</option><option value="90">90 minutes</option></select></label><label>Date *<input name="date" type="date" required></label><label>Time *<input name="time" type="time" required></label><input type="hidden" name="timezone" value="${escapeHtml_(timezone)}"><label class="wide">Message<textarea name="note" maxlength="500" placeholder="Anything Pratik should know?"></textarea></label><button type="submit">Send booking request</button></form></main></body></html>`
}
function successPage_(request){return messagePage_('Request sent','Your request for '+escapeHtml_(request.date)+' at '+escapeHtml_(request.time)+' is waiting for approval.','#2bd576')}
function messagePage_(title,message,color){return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{min-height:100vh;display:grid;place-items:center;margin:0;background:#071426;color:#edf4ff;font:16px system-ui;text-align:center;padding:20px}main{max-width:520px;padding:30px;border:1px solid #284568;border-radius:22px;background:#0d213c}h1{color:${color}}p{color:#aebfd5;line-height:1.6}</style></head><body><main><h1>${title}</h1><p>${message}</p><p>You may close this page.</p></main></body></html>`}
