const CACHE="pratiks-progress-plan-v35-gemini-entry-logic";
const ASSETS=[
  "./",
  "./index.html",
  "./manifest.json",
  "./icon.svg",
  "./styles/main.css",
  "./scripts/components.js",
  "./scripts/config.js",
  "./scripts/state.js",
  "./scripts/analytics.js",
  "./scripts/dashboard.js",
  "./scripts/routine.js",
  "./scripts/activity.js",
  "./scripts/diary.js",
  "./scripts/library.js",
  "./scripts/music.js",
  "./scripts/bookings.js",
  "./scripts/quotes.js",
  "./scripts/ui.js",
  "./scripts/app.js",
  "./components/layout/header.html",
  "./components/layout/hero.html",
  "./components/layout/navigation.html",
  "./components/layout/footer.html",
  "./components/sections/dashboard.html",
  "./components/sections/today.html",
  "./components/sections/calendar.html",
  "./components/sections/plan.html",
  "./components/sections/routine.html",
  "./components/sections/activity.html",
  "./components/sections/diary.html",
  "./components/sections/library.html",
  "./components/sections/bookings.html",
  "./components/sections/insights.html",
  "./components/sections/settings.html",
  "./components/overlays/quick-checkin.html",
  "./components/overlays/plan-progress.html",
  "./components/overlays/feedback.html"
];
self.addEventListener("install",e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)))});
self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener("fetch",e=>{
  if(e.request.method!=="GET")return;
  e.respondWith(fetch(e.request).then(response=>{if(response&&response.ok){const copy=response.clone();e.waitUntil(caches.open(CACHE).then(cache=>cache.put(e.request,copy)))}return response}).catch(async()=>await caches.match(e.request)||await caches.match(new URL(e.request.url).pathname.endsWith("/")?"./":"./index.html")));
});
